import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Home, ClipboardList, Camera, Package, Hammer, CalendarClock, Users, MessageCircle, Plus, Search, Filter, AlertTriangle, Languages, CheckCircle2, Star } from 'lucide-react';
import './styles.css';

const seedTasks = [
  { title: 'Terminar pintura del baño', property: 'Estudio / Ocean View', priority: 'Alta', status: 'En progreso', assignee: 'Mantenimiento', due: 'Esta semana', impact: 'Alto', cost: 'Opcional', type: 'Proyecto' },
  { title: 'Revisar y cargar bombas de garrafón', property: 'Estudio / Ocean View', priority: 'Media', status: 'Pendiente', assignee: 'Encargado', due: 'Hoy', impact: 'Medio', cost: '—', type: 'Tarea' },
  { title: 'Instalar placa en baño exterior', property: 'Spa House', priority: 'Media', status: 'Pendiente', assignee: 'Mantenimiento', due: 'Mayo', impact: 'Rápido', cost: 'Opcional', type: 'Tarea' },
  { title: 'Podar palmeras', property: 'Spa House', priority: 'Media', status: 'Programado', assignee: 'Jardinero', due: 'Este mes', impact: 'Medio', cost: 'Opcional', type: 'Exterior' },
];
const inventory = [['Papel de baño','Bajo','Todos','Comprar','Opcional'],['Toallas de papel','Medio','Todos','Comprar','Opcional'],['Jabón de manos','Bajo','Estudio','Revisar','Opcional'],['Detergente de ropa','Bajo','Spa House','Comprar','Opcional'],['Shampoo / body wash / acondicionador','Bajo','Todos','Comprar','Opcional'],['Aceite, sal y pimienta','Medio','Todos','Revisar','Opcional']];
const maintenance = [['Fumigación','Marzo 2026','Junio 2026','Cada 3 meses'],['Gas propano','Mayo 2026','Cuando esté bajo','Según uso'],['Limpieza de AC','Abril 2026','Julio 2026','Cada 3 meses'],['Impermeabilización del techo','Septiembre 2025','Antes de lluvias','Anual / según condición'],['Ventanas difíciles','Mayo 2026','Nov 2026 - May 2027','Antes de temporada alta']];
const projects = [['Repisas arriba del baño','Estudio','Lista de deseos','Media','Medio'],['Agregar perchero / rack de ropa','Estudio','No urgente','Baja','Rápido'],['Agregar barras para toallas','Spa House','No urgente','Media','Rápido'],['Impermeabilizar techo','Spa House','Planificado','Alta','Alto']];

function Badge({ children, tone = 'slate' }) { return <span className={`badge ${tone}`}>{children}</span>; }
function Button({ children, onClick, secondary }) { return <button onClick={onClick} className={secondary ? 'btn secondary' : 'btn'}>{children}</button>; }
function Card({ children }) { return <div className="card">{children}</div>; }
function SectionTitle({ icon: Icon, title, subtitle }) { return <div className="section-title"><div className="title-icon"><Icon size={20}/></div><div><h2>{title}</h2><p>{subtitle}</p></div></div>; }
function TaskRow({ t }) { return <div className="task-row"><div><div className="badges"><Badge tone={t.priority === 'Alta' ? 'red' : 'amber'}>{t.priority}</Badge><Badge>{t.status}</Badge><Badge tone="green">Impacto {t.impact}</Badge></div><h3>{t.title}</h3><p>{t.property} · Responsable: {t.assignee} · Fecha: {t.due}</p></div><div className="row-actions"><Button secondary><MessageCircle size={16}/> WhatsApp</Button><Button>Abrir</Button></div></div>; }

function App() {
  const [tab, setTab] = useState('inicio');
  const [lang, setLang] = useState('ES');
  const nav = [['inicio', Home, 'Inicio'],['tareas', ClipboardList, 'Tareas'],['limpiezas', Camera, 'Limpiezas'],['inventario', Package, 'Inventario'],['proyectos', Hammer, 'Proyectos'],['historial', CalendarClock, 'Historial'],['equipo', Users, 'Equipo']];
  const currentTitle = useMemo(() => nav.find(n => n[0] === tab)?.[2] || 'Inicio', [tab]);
  return <div className="app"><aside><div className="brand"><div><h1>CasaOps</h1><p>Airbnb · Español primero</p></div><Button secondary onClick={() => setLang(lang === 'ES' ? 'EN' : 'ES')}><Languages size={16}/>{lang}</Button></div><nav>{nav.map(([id, Icon, label]) => <button key={id} onClick={() => setTab(id)} className={tab===id?'active':''}><Icon size={20}/>{label}</button>)}</nav><div className="checkin"><b>Próximo check-in</b><strong>Hoy 3:00 PM</strong><span>Confirmar limpieza + fotos finales</span></div></aside><main><header><div><p>Panel principal</p><h1>{currentTitle}</h1></div><div className="actions"><Button secondary><Search size={16}/>Buscar</Button><Button secondary><Filter size={16}/>Filtros</Button><Button><Plus size={16}/>Nuevo</Button></div></header>{tab==='inicio'&&<Inicio/>}{tab==='tareas'&&<TaskList/>}{tab==='limpiezas'&&<Cleaning/>}{tab==='inventario'&&<Inventory/>}{tab==='proyectos'&&<Projects/>}{tab==='historial'&&<History/>}{tab==='equipo'&&<Team/>}</main></div>;
}
function Inicio(){return <div className="stack"><div className="metrics"><Card><AlertTriangle/><p>Urgente</p><h2>3</h2></Card><Card><Camera/><p>Limpiezas hoy</p><h2>2</h2></Card><Card><Package/><p>Inventario bajo</p><h2>6</h2></Card><Card><Star/><p>Mejor ROI rápido</p><h2>5</h2></Card></div><Card><SectionTitle icon={Star} title="Mejor para aumentar ingresos pronto" subtitle="Tareas con alto impacto en fotos, reseñas o reservas"/><div className="grid2">{seedTasks.filter(t=>['Alto','Rápido'].includes(t.impact)).map((t,i)=><div className="mini" key={i}><div><b>{t.title}</b><p>{t.property} · {t.due}</p></div><Badge tone="green">{t.impact}</Badge></div>)}</div></Card><Card><SectionTitle icon={ClipboardList} title="Tareas activas" subtitle="Vista rápida de operaciones"/>{seedTasks.map((t,i)=><TaskRow key={i} t={t}/>)}</Card></div>}
function TaskList(){return <Card><SectionTitle icon={ClipboardList} title="Tareas" subtitle="Prioridad, responsable, fechas, propiedad, costo opcional e impacto en ingresos"/>{seedTasks.map((t,i)=><TaskRow key={i} t={t}/>)}</Card>}
function Cleaning(){const steps=['Fotos ANTES obligatorias','Checklist de limpieza','Inventario rápido','Fotos DESPUÉS obligatorias','Aprobación del encargado','Listo para check-in'];return <div className="stack"><Card><SectionTitle icon={Camera} title="Limpiezas" subtitle="Flujo obligatorio con fotos antes y después"/><div className="grid3">{steps.map((s,i)=><div className="step" key={s}><span>{i+1}</span><b>{s}</b><p>{i===0||i===3?'No se puede completar sin fotos':'Paso requerido'}</p></div>)}</div></Card><Card><h2>Confirmar listo para huésped</h2><div className="grid2">{['Camas listas','Baño limpio','Toallas y papel de baño','AC funciona','Cerradura funciona','Agua / garrafón listo','Luces funcionan','Fotos finales subidas'].map(x=><div className="check" key={x}><CheckCircle2 size={18}/>{x}</div>)}</div></Card></div>}
function Inventory(){return <Card><SectionTitle icon={Package} title="Inventario / Compras" subtitle="Costos opcionales, cantidades, proveedor y recibos si están disponibles"/>{inventory.map(([item,stock,property,status,cost])=><div className="mini" key={item}><div><b>{item}</b><p>{property} · Estado: {status} · Costo: {cost}</p></div><Badge tone={stock==='Bajo'?'red':'amber'}>{stock}</Badge></div>)}</Card>}
function Projects(){return <Card><SectionTitle icon={Hammer} title="Proyectos / Lista de deseos" subtitle="Urgente, no urgente, timeline, costo opcional e impacto en ingresos"/><div className="grid2">{projects.map(([name,prop,status,priority,impact])=><div className="project" key={name}><div className="badges"><Badge tone={priority==='Alta'?'red':priority==='Media'?'amber':'slate'}>{priority}</Badge><Badge tone="green">Impacto {impact}</Badge></div><h3>{name}</h3><p>{prop} · {status}</p></div>)}</div></Card>}
function History(){return <Card><SectionTitle icon={CalendarClock} title="Historial de mantenimiento" subtitle="Última vez que se hizo y próxima fecha recomendada"/><table><thead><tr><th>Item</th><th>Última vez</th><th>Próxima</th><th>Frecuencia</th></tr></thead><tbody>{maintenance.map(m=><tr key={m[0]}><td><b>{m[0]}</b></td><td>{m[1]}</td><td>{m[2]}</td><td>{m[3]}</td></tr>)}</tbody></table></Card>}
function Team(){const people=[['Rebecca','Dueña / Admin','Todo'],['Encargado onsite','Property Manager','Asignar limpiezas, confirmar check-in'],['Cleaner','Limpieza','Ver tareas, subir fotos'],['Mantenimiento','Reparaciones','Completar tareas, subir costos opcionales']];return <Card><SectionTitle icon={Users} title="Equipo y permisos" subtitle="Cada persona ve solo lo que necesita"/><div className="grid2">{people.map(([name,role,perm])=><div className="project" key={name}><h3>{name}</h3><p>{role}</p><span>{perm}</span></div>)}</div></Card>}

createRoot(document.getElementById('root')).render(<App />);
